(define (problem PUZZLE)
(:domain PUZZLE)
(:objects p1 p2 p3 p4 p5 p6 p7 p8 p9 - position c1 c2 c3 c4 c5 c6 c7 c8 - case)

(:init  (on p1 c3)
        (on p2 c7)
        (on p3 c5)
        (on p5 c1)
        (on p6 c2)
        (on p7 c8)
        (on p8 c4)
        (on p9 c6)
        (clear p4)
        (close p1 p2)
        (close p1 p4)
        (close p2 p1)
        (close p2 p3)
        (close p2 p5)
        (close p3 p2)
        (close p3 p6)
        (close p4 p1)
        (close p4 p5)
        (close p4 p7)
        (close p5 p2)
        (close p5 p4)
        (close p5 p6)
        (close p5 p8)
        (close p6 p3)
        (close p6 p5)
        (close p6 p9)
        (close p7 p4)
        (close p7 p8)
        (close p8 p5)
        (close p8 p7)
        (close p8 p9)
        (close p9 p6)
        (close p9 p8)
)

(:goal  (and (on p1 c1)
        (on p2 c2)
        (on p3 c3)
        (on p4 c4)
        (on p5 c5)
        (on p6 c6)
        (on p7 c7)
        (on p8 c8)
        (clear p9)))
)
