(define (problem COLORING)
    (:domain COLORING)
    (:objects v1 v2 v3 v4 v5 - node c1 c2 c3 - color)

    (:init  (adjacent v1 v3)
            (adjacent v3 v1)
            (adjacent v2 v3)
            (adjacent v3 v2)
            (adjacent v3 v4)
            (adjacent v3 v5)
            (adjacent v4 v3)
            (adjacent v5 v3)
            (adjacent v5 v4)
            (adjacent v4 v5)
    )

    (:goal  
        (and 
            (colored v1)
            (colored v2)
            (colored v3)
            (colored v4)
            (colored v5)
        )
    )
)
