(define (problem coloriage-graphe-3)
  (:domain coloriage-graphe)
  (:objects A B C D E F - noeud ROUGE VERT BLEU JAUNE - couleur AB AC AD BC BD CD DE EF - arete)
  (:init
    (adjacent A B AB)
    (adjacent A C AC)
    (adjacent A D AD)
    (adjacent B C BC)
    (adjacent B D BD)
    (adjacent C D CD)
    (adjacent D E DE)
    (adjacent E F EF)
    (non-colorie A)
    (non-colorie B)
    (non-colorie C)
    (non-colorie D)
    (non-colorie E)
    (non-colorie F)
    (non-marquee AB)
    (non-marquee AC)
    (non-marquee AD)
    (non-marquee BC)
    (non-marquee BD)
    (non-marquee CD)
    (non-marquee DE)
    (non-marquee EF)
    (couleur-differente ROUGE VERT)
    (couleur-differente ROUGE BLEU)
    (couleur-differente ROUGE JAUNE)
    (couleur-differente VERT BLEU)
    (couleur-differente VERT JAUNE)
    (couleur-differente BLEU JAUNE)
    (couleur-differente BLEU ROUGE)
    (couleur-differente JAUNE ROUGE)
    (couleur-differente JAUNE VERT)
  )
  (:goal (and
    (colorie A ROUGE)
    (colorie B VERT)
    (colorie C BLEU)
    (colorie D JAUNE)
    (colorie E ROUGE)
    (colorie F VERT)
  ))
)
